import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { LoginSuccessToast } from "@/components/auth/LoginSuccessToast";
import { DevNav } from "@/components/dev/DevNav";
import { Header } from "@/components/layout/Header";
import { AppToaster } from "@/components/providers/AppToaster";
import { LanguageProvider } from "@/components/providers/LanguageProvider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <LanguageProvider>
          <DevNav />
          <Header />
          {children}
          <AppToaster />
          <LoginSuccessToast />
        </LanguageProvider>
      </body>
    </html>
  );
}
